LEEJESEOK/KOSA-Final

pom.xml, src/main/java/com/hyundai/kosafinal/config/XssConfig.java, src/main/resources/lucy-xss-servlet-filter-rule.xml, src/main/resources/lucy-xss-superset-sax.xml
=> [KF-33] Spring XSS설정 및 POM.XML 수정

pom.xml
=> fixed: XSS 의존성 버전 변경

src/main/java/com/hyundai/kosafinal/common/TestCommon.java, src/main/java/com/hyundai/kosafinal/controller/HomeController.java, src/main/java/com/hyundai/kosafinal/domain/TestDomain.java, src/main/java/com/hyundai/kosafinal/entity/TestEntity.java, src/main/java/com/hyundai/kosafinal/mapper/TestMapper.java, src/main/java/com/hyundai/kosafinal/security/TestSecurity.java, src/main/java/com/hyundai/kosafinal/service/TestService.java
=> [KF-34] 프로젝트 패키지 생성

src/main/java/com/hyundai/kosafinal/domain/CartDTO.java, src/main/java/com/hyundai/kosafinal/domain/CategoryDTO.java, src/main/java/com/hyundai/kosafinal/domain/ColorDTO.java, src/main/java/com/hyundai/kosafinal/domain/GradeDTO.java, src/main/java/com/hyundai/kosafinal/domain/MypageReviewDTO.java, src/main/java/com/hyundai/kosafinal/domain/OrderItemDTO.java, src/main/java/com/hyundai/kosafinal/domain/OrderedListDTO.java, src/main/java/com/hyundai/kosafinal/domain/ProductDTO.java, src/main/java/com/hyundai/kosafinal/domain/ProductReviewDTO.java, src/main/java/com/hyundai/kosafinal/domain/ReplyDTO.java, src/main/java/com/hyundai/kosafinal/domain/RoleSetDTO.java, src/main/java/com/hyundai/kosafinal/domain/UserDTO.java
=> KF-37 - KF-37-dto-패키지-수정

src/main/java/com/hyundai/kosafinal/domain/CartDTO.java, src/main/java/com/hyundai/kosafinal/domain/CategoryDTO.java, src/main/java/com/hyundai/kosafinal/domain/ColorDTO.java, src/main/java/com/hyundai/kosafinal/domain/GradeDTO.java, src/main/java/com/hyundai/kosafinal/domain/MypageReviewDTO.java, src/main/java/com/hyundai/kosafinal/domain/OrderItemDTO.java, src/main/java/com/hyundai/kosafinal/domain/OrderedListDTO.java, src/main/java/com/hyundai/kosafinal/domain/ProductDTO.java, src/main/java/com/hyundai/kosafinal/domain/ProductReviewDTO.java, src/main/java/com/hyundai/kosafinal/domain/ReplyDTO.java, src/main/java/com/hyundai/kosafinal/domain/UserDTO.java
=> KF-37 - KF-37-클래스명-DTO-추가

.gitignore, src/main/java/com/hyundai/kosafinal/config/ProductDatabaseConfig.java, src/main/java/com/hyundai/kosafinal/config/UserOrderDatabaseConfig.java, src/main/java/com/hyundai/kosafinal/mapper/product/ProductMapper.java, src/main/java/com/hyundai/kosafinal/mapper/userorder/UserOrderMapper.java, src/main/resources/application.properties, src/main/resources/mybatis/mapper-config.xml, src/main/resources/mybatis/mapper/product/ProductMapper.xml, src/main/resources/mybatis/mapper/userorder/UserOrderMapper.xml, src/test/java/com/hyundai/kosafinal/dbTest/DataSourceTests.java
application.properties에서 DB 분리 작업 및 config 설정
=> [KF-35] DB 분리 작업

src/main/java/com/hyundai/kosafinal/domain/CartDTO.java, src/main/java/com/hyundai/kosafinal/domain/CategoryDTO.java, src/main/java/com/hyundai/kosafinal/domain/ColorDTO.java, src/main/java/com/hyundai/kosafinal/domain/GradeDTO.java, src/main/java/com/hyundai/kosafinal/domain/MemberDTO.java, src/main/java/com/hyundai/kosafinal/domain/MypageReviewDTO.java, src/main/java/com/hyundai/kosafinal/domain/OrderItemDTO.java, src/main/java/com/hyundai/kosafinal/domain/OrderedListDTO.java, src/main/java/com/hyundai/kosafinal/domain/ProductDTO.java, src/main/java/com/hyundai/kosafinal/domain/ProductReviewDTO.java, src/main/java/com/hyundai/kosafinal/domain/ReplyDTO.java, src/main/java/com/hyundai/kosafinal/domain/RoleSetDTO.java
=> [KF-39] DTO 어노테이션 추가 및 클래스명 변경

src/main/resources/application.properties
datasource url 수정
url -> jdbc-url
=> KF-35 jdbc-url 수정

src/main/java/com/hyundai/kosafinal/config/ProductDatabaseConfig.java, src/main/java/com/hyundai/kosafinal/config/UserOrderDatabaseConfig.java, src/main/java/com/hyundai/kosafinal/domain/CategoryDTO.java, src/main/java/com/hyundai/kosafinal/domain/Criteria.java, src/main/java/com/hyundai/kosafinal/domain/ProductDTO.java, src/main/java/com/hyundai/kosafinal/mapper/product/ProductMapper.java, src/main/resources/mybatis/mapper-config.xml, src/main/resources/mybatis/mapper/product/ProductMapper.xml, src/test/java/com/hyundai/kosafinal/mapper/product/ProductMapperTest.java
=> KF-43 - Mybatis type alias 설정

src/main/java/com/hyundai/kosafinal/config/UserOrderDatabaseConfig.java, src/main/resources/application.properties, src/main/resources/mybatis/mapper-config.xml
=> [KF-44] mybatis-config.xml 카멜변환 설정 추가

src/main/resources/templates/mypage/reviewInsert.html, src/main/resources/templates/mypage/reviewInsertComplete.html
=> [KF-9] 1:1 문의(고객센터) - 문의 등록 페이지

src/main/resources/templates/head.html
=> KF-48 HEAD fragment

src/main/resources/application.properties
=> KF-49 기본 포트 변경

src/main/java/com/hyundai/kosafinal/controller/ProductController.java, src/main/java/com/hyundai/kosafinal/controller/ProductRestController.java, src/main/resources/mybatis/mapper/product/ProductMapper.xml, src/main/resources/static/css/common.css, src/main/resources/static/css/contents.css, src/main/resources/static/css/product.css, src/main/resources/static/css/products.css, src/main/resources/templates/category.html, src/main/resources/templates/head.html, src/test/java/com/hyundai/kosafinal/service/ProductServiceTest.java
카테고리 리스트 구현
- TODO
- 상품 색 변경
- 사이즈 조회
=> KF-7 카테고리 리스트

src/main/java/com/hyundai/kosafinal/config/UserOrderDatabaseConfig.java, src/main/java/com/hyundai/kosafinal/controller/CartController.java, src/main/java/com/hyundai/kosafinal/controller/IndexController.java, src/main/java/com/hyundai/kosafinal/domain/CartDTO.java, src/main/java/com/hyundai/kosafinal/entity/CartProduct.java, src/main/java/com/hyundai/kosafinal/mapper/userorder/CartMapper.java, src/main/java/com/hyundai/kosafinal/service/CartService.java, src/main/java/com/hyundai/kosafinal/service/CartServiceImpl.java, src/main/resources/mybatis/mapper/userorder/CartMapper.xml, src/test/java/com/hyundai/kosafinal/mapper/product/ProductMapperTest.java, src/test/java/com/hyundai/kosafinal/mapper/userorder/CartMapperTest.java
=> [KF-46] 장바구니 - 장바구니 CRUD API

src/main/resources/templates/cart/cartList.html, src/main/resources/templates/mypage/reviewInsert.html, src/main/resources/templates/mypage/reviewInsertComplete.html, src/main/resources/templates/mypage/reviewList.html
=> [KF-47] 장바구니 - 장바구니 페이지

src/main/java/com/hyundai/kosafinal/KosaFinalApplication.java, src/main/java/com/hyundai/kosafinal/config/SecurityConfig.java, src/main/java/com/hyundai/kosafinal/controller/HomeController.java, src/main/resources/static/js/search.js, src/main/resources/templates/head.html, src/main/resources/templates/header_logo.html, src/main/resources/templates/mypage/reviewInsert.html
- head.html
- meta 정보에 csrf 토큰 추가
- ajax 실행하기 전 ajaxSetup에서 csrf 설정
=> KF-52 CSRF 적용

src/main/resources/static/css/footer.css, src/main/resources/static/css/layout.css, src/main/resources/static/css/products.css
- products, layout, footer
- 이미지 url 수정
=> KF-69 CSS 이미지 참조 경로 수정

src/main/java/com/hyundai/kosafinal/config/SecurityConfig.java, src/main/java/com/hyundai/kosafinal/controller/MemberController.java, src/main/resources/templates/member/login.html, src/main/resources/templates/member/signUp.html, src/main/resources/templates/mypage/reviewInsert.html, src/main/resources/templates/top_nav.html
=> KF-22 로그인, 로그아웃 CSRF 적용

src/main/resources/templates/mypage/myorder.html, src/main/resources/templates/mypage/myorderDetail.html, src/main/resources/templates/order/orderComplete.html, src/main/resources/templates/order/orderForm.html
=> KF-55 주문 페이지

src/main/java/com/hyundai/kosafinal/controller/MypageController.java, src/main/java/com/hyundai/kosafinal/controller/OrderRestController.java, src/main/java/com/hyundai/kosafinal/mapper/userorder/OrderMapper.java, src/main/java/com/hyundai/kosafinal/service/MemberService.java, src/main/java/com/hyundai/kosafinal/service/OrderService.java, src/main/java/com/hyundai/kosafinal/service/OrderServiceImpl.java, src/main/resources/mybatis/mapper/userorder/OrderMapper.xml, src/main/resources/templates/cart/cartList.html, src/main/resources/templates/gnbwarp_image.html, src/main/resources/templates/gnbwarp_menu.html, src/main/resources/templates/top_nav.html
=> KF-83 주문 전 재고확인

src/main/java/com/hyundai/kosafinal/controller/CartRestController.java, src/main/java/com/hyundai/kosafinal/domain/OrderedListDTO.java, src/main/resources/templates/cart/cartList.html, src/main/resources/templates/mypage/myorder.html, src/main/resources/templates/mypage/myorderDetail.html, src/main/resources/templates/order/orderComplete.html, src/test/java/com/hyundai/kosafinal/mapper/userorder/OrderMapperTest.java
주문번호 컬럼(order_id) 추가
YYYYMMDDHid 형식
=> KF-84 주문번호 추가

src/main/java/com/hyundai/kosafinal/controller/ProductReviewController.java, src/main/java/com/hyundai/kosafinal/controller/ProductWebController.java, src/main/resources/static/js/add.js, src/main/resources/templates/index.html
=> KF-95-review수정

src/main/java/com/hyundai/kosafinal/controller/MypageController.java, src/main/resources/mybatis/mapper/userorder/OrderMapper.xml, src/main/resources/templates/mypage/myorderDetail.html
=> 주문조회 버그 수정

src/main/java/com/hyundai/kosafinal/config/CustomAuthenticationSuccessHandler.java, src/main/java/com/hyundai/kosafinal/controller/MemberRestController.java, src/main/resources/static/css/common.css, src/main/resources/static/css/footer.css, src/main/resources/static/css/import.css, src/main/resources/static/css/layout.css, src/main/resources/templates/fragment/footer.html, src/main/resources/templates/fragment/gnbwarp_menu.html, src/main/resources/templates/fragment/top_nav.html, src/main/resources/templates/index.html, src/main/resources/templates/mypage/modify.html
=> KF-110-로그인관련버그수정

src/main/java/com/hyundai/kosafinal/controller/ProductReviewController.java, src/main/resources/templates/fragment/gnbwarp_menu.html
=> KF-110-main수정

src/main/resources/templates/fragment/gnbwarp_menu.html
=> top_nav 링크 # 수정

src/main/resources/templates/error/All_error.html, src/main/resources/templates/fragment/gnbwarp_image.html, src/main/resources/templates/fragment/top_nav.html
=> KF-115-top_nav.html 수정

src/main/java/com/hyundai/kosafinal/controller/ProductReviewController.java
=> ReviewController 로직 최종 변경
